version: '3.9'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      context: ./server
      dockerfile: ${DOCKERFILE_SERVER}
    volumes:
      - ./server:/proyectoAPI
      - /proyectoAPI/node_modules
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client
      dockerfile: ${DOCKERFILE_CLIENT}
    volumes:
      - ./client:/proyectoClient
      - /proyectoClient/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
volumes:
  db: