version: '3.9'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './:/api'
      - '/api/node_modules'
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '180:180'
    environment:
      - NODE_ENV=development
volumes:
  db: